# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_member_id', models.DecimalField(decimal_places=0, max_digits=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.CastMember')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotten_tomatoes_id', models.DecimalField(decimal_places=0, max_digits=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('mpaa_rating', models.CharField(max_length=255)),
                ('runtime', models.DecimalField(decimal_places=0, max_digits=4)),
                ('theatre_release_date', models.DateField()),
                ('synopsis', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critics_rating', models.CharField(max_length=255)),
                ('critics_score', models.DecimalField(decimal_places=0, max_digits=100)),
                ('audience_score', models.DecimalField(decimal_places=0, max_digits=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='castmember',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
