# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmember',
            name='cast_member_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='audience_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='critics_score',
            field=models.IntegerField(),
        ),
    ]
