# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160221_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='synopsis',
        ),
    ]
