# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20160222_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rotten_tomatoes_id',
            field=models.DecimalField(decimal_places=0, max_digits=255, unique=True),
        ),
    ]
