# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20160223_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='audience_score',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='movie',
            name='critics_rating',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='critics_score',
            field=models.IntegerField(default='-1'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
