# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20160223_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='extrathing',
        ),
    ]
