# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_extrathing'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumb',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
